[tool.ruff]
extend-exclude = ["*.ipynb", "cmake"]

[tool.ruff.lint]
extend-ignore = ["RUF012", "UP036"]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.ruff.lint.isort]
known-first-party = ["crocoddyl"]

[tool.tomlsort]
all = true
